required-players: 2
countdown-seconds: 30
lobby-spawn:
  world: 'world'
  x: 164.5
  y: 71.5
  z: -3.5
  yaw: -180
  pitch: 0
arenas:
  0:
    world: 'Snow'
    x: 4.5
    y: 4
    z: -69.5
    yaw: 90
    pitch: 0
  1:
    world: 'Desert'
    x: 4.5
    y: 4
    z: -69.5
    yaw: 90
    pitch: 0
