required-players: 2
countdown-seconds: 30
arenas:
  0:
    sign:
      world: 'world'
      x: 166
      y: 72
      z: -5
    player-spawn:
      world: 'world'
      x: 4.5
      y: 4
      z: -69.5
  1:
    sign:
      world: 'world'
      x: 166
      y: 72
      z: -5
    player-spawn:
      world: 'world'
      x: 4.5
      y: 4
      z: -69.5
