required-players: 2
countdown-seconds: 30
arenas:
   0:
    game: 'BLOCK'
    world: 'world'
    x: 166
    y: 72
    z: -5
    yaw: -180
    pitch: 0
   1:
    game: 'PVP'
    world: 'world'
    x: 173.5
    y: 69
    z: -14.5
    yaw: -180
    pitch: 0
